image:
  file: Dockerfile
tasks:
  - name: Install Nextflow
    init: curl -s https://get.nextflow.io | bash
    command: sudo mv nextflow /usr/local/bin
  - name: Install Miniconda
    command: chmod +x envconfig.sh 
