image:
  file: Dockerfile
tasks:
  - name: Install Nextflow
    init: curl -s https://get.nextflow.io | bash
    command: sudo mv nextflow /usr/local/bin
  - name: Set Perm
    command: chmod +x envconfig.sh 
  - name: Install nf-core
    init: pip install nf-core
  - name: Install graphviz
    init: pip install graphviz
